# Generated by Django 3.0.3 on 2020-03-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='nickname',
            field=models.CharField(default='My Dude', max_length=20),
        ),
    ]
