# Generated by Django 3.0.3 on 2020-03-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200320_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='move',
            name='m_type',
            field=models.CharField(default='Normal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='name',
            field=models.CharField(default='Move', max_length=20),
            preserve_default=False,
        ),
    ]
