# Generated by Django 3.0.3 on 2020-03-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200321_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(to='main_app.Move'),
        ),
    ]
